Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 60
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUel: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExtx:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: postgres
  Host: 127.0.0.1
  Port: 5432
  DB: blog
  User: postgres
  Password: postgres