Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 60
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUel: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .JPG
    - .JPEG
    - .PNG
  DefaultContextTimeout: 60
Database:
  DBType: postgres
  Host: 127.0.0.1
  Port: 5432
  DB: blog
  User: postgres
  Password: postgres
JWT:
  Secret: Arnold
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.live.com
  Port: 587
  UserName: XXXX@hotmail.com
  Password: 
  IsSSL: true
  From: XXXX@hotmail.com
  To:
    - XXXX@hotmail.com
